_veh = _this select 0;
_gunner = gunner _veh;
_weapon = _veh currentWeaponTurret [0];
_veh addeventhandler ["fired", {(_this select 0) setvehicleammo 1}];
_grp = createGroup west;
_AAposition1 = _grp createUnit ["C_Soldier_VR_F", position _veh, [], 0, "FORM"];  
_AAposition2 = _grp createUnit ["C_Soldier_VR_F", position _veh, [], 0, "FORM"];  
_AAposition3 = _grp createUnit ["C_Soldier_VR_F", position _veh, [], 0, "FORM"];  

[ 
 [_AAposition1, true], 
 "hideObjectGlobal" 
] call BIS_fnc_MP;
[ 
 [_AAposition2, true], 
 "hideObjectGlobal" 
] call BIS_fnc_MP;
[ 
 [_AAposition3, true], 
 "hideObjectGlobal" 
] call BIS_fnc_MP;

_AAposition1 attachTo [_veh, [120, 50, 60] ]; 
_AAposition2 attachTo [_veh, [-120, 50, 60] ]; 
_AAposition3 attachTo [_veh, [122, -50, 60] ]; 

while {alive _veh} do {

_gunner doWatch _AAposition1;
_veh doWatch _AAposition1;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;

sleep 0.1;
_gunner doWatch _AAposition2;
sleep 3.9;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;

sleep 0.1;
_gunner doWatch _AAposition3;
sleep 3.9;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;
sleep 0.1;
_veh fire _weapon;

sleep 0.1;
sleep 4;
};