player removeItems "ACE_adenosine";
player removeItems "ACE_bloodIV";
player removeItems "ACE_bloodIV_250";
player removeItems "ACE_bloodIV_500";
player removeItems "ACE_plasmaIV";
player removeItems "ACE_plasmaIV_250";
player removeItems "ACE_plasmaIV_500";
player removeItems "ACE_surgicalKit";
player removeItems "ACE_salineIV";
player removeItems "ACE_salineIV_250";
player removeItems "ACE_salineIV_500";
player removeItems "ACE_personalAidKit";
player removeItems "ACE_epinephrine";
player removeItems "ACE_splint";
player removeItems "ACE_morphine";
player removeItems "ACE_quikclot";
player removeItems "ACE_packingBandage";
player removeItems "ACE_elasticBandage";
player removeItems "ACE_tourniquet";
player removeItems "ACE_atropine";
player removeItems "ACE_atropine";
player removeItems "ItemGPS";
player removeItems "ItemMap";
player removeItems "tf_microdagr";
player removeWeapon "SWLB_clone_binocular";
player removeMagazines "SWLW_DC15A_Mag";
player removeWeapon "ls_weapon_dc15a";
player addBackpack "SWLB_clone_backpack";
player addItem "ls_gar_cadet_helmet";
player assignItem "ls_gar_cadet_helmet";
player addItem "SWLB_clone_basic_armor";
player assignItem "SWLB_clone_basic_armor";
player addItem "SWLB_clone_nvg";
player assignItem "SWLB_clone_nvg";
player addWeapon "SWLB_clone_binocular";
player addItem "ItemMap";
player assignItem "ItemMap";
player addItem "ItemGPS";
player assignItem "ItemGPS";
player addItem "SWLB_comlink";
player assignItem "SWLB_comlink";
player addItem "ItemCompass";
player assignItem "ItemCompass";
player addItem "tf_microdagr";
player assignItem "tf_microdagr";
player addWeapon "ls_weapon_dc15a";
for "_i" from 1 to 7 do {player addItem "SWLW_DC15A_Mag";};
for "_i" from 1 to 4 do {player addItem "ACE_epinephrine";};
for "_i" from 1 to 4 do {player addItem "ACE_morphine";};
for "_i" from 1 to 4 do {player addItem "ACE_tourniquet";};
for "_i" from 1 to 16 do {player addItem "ACE_elasticBandage";};
for "_i" from 1 to 12 do {player addItem "ACE_packingBandage";};
for "_i" from 1 to 12 do {player addItem "ACE_fieldDressing";};
for "_i" from 1 to 2 do {player addItem "ACE_salineIV_250";};
for "_i" from 1 to 4 do {player addItem "ACE_splint";};